name: Build images-to-azure-storage-account

on:
  push:
    paths:
      - .github/workflows/images-to-azure-storage-account.yml
      - images-to-azure-storage-account/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: images-to-azure-storage-account
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - run: az bicep build --file main.bicep
