name: Build images-to-azure-storage-account

on:
  push:
    paths:
      - .github/workflows/images-to-azure-storage-account.yml
      - images-to-azure-storage-account/**
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: main/images-to-azure-storage-account
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
      - uses: actions/checkout@v2
        with:
          repository: Azure/arm-ttk
          ref: 32a30b8472d4beb5c702a0853c14d5af8991a1e2
          path: arm-ttk
      - shell: pwsh
        run: |
          Import-Module ..\..\arm-ttk\arm-ttk\arm-ttk.psd1
          Test-AzTemplate -TemplatePath .
