name: Build images-to-azure-storage-account

on:
  push:
    paths:
      - .github/workflows/images-to-azure-storage-account.yml
      - images-to-azure-storage-account/**
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: main/images-to-azure-storage-account
    steps:
      - run: dir /s /b
      - uses: actions/checkout@v2
        with:
          path: main
      - run: dir /s /b
      - uses: actions/checkout@v2
        with:
          repository: Azure/arm-ttk
          path: arm-ttk
      - run: dir /s /b
      - shell: pwsh
        run: |
          Import-Module ..\..\arm-ttk\arm-ttk\arm-ttk.psd1
          Test-AzTemplate -TemplatePath .
