name: Build images-to-azure-storage-account

on:
  push:
    paths:
      - .github/workflows/images-to-azure-storage-account.yml
      - images-to-azure-storage-account/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: images-to-azure-storage-account
    steps:
      - uses: actions/checkout@v2
      - run: az bicep build --file main.bicep
