name: Build images-to-azure-storage-account

on:
  push:
    paths:
      - .github/workflows/images-to-azure-storage-account.yml
      - images-to-azure-storage-account/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: images-to-azure-storage-account
    steps:
      - uses: actions/checkout@v2
      - run: az bicep build --file main.bicep
      - run: ../scripts/assert-azure-deploy-uri.sh README.md https%3A%2F%2Fraw.githubusercontent.com%2FAxisCommunications%2Facap-integration-examples-azure%2Fmain%2Fimages-to-azure-storage-account%2Fmain.json
