name: Build telemetry-to-azure-iot-hub

on:
  push:
    paths:
      - .github/workflows/telemetry-to-azure-iot-hub.yml
      - telemetry-to-azure-iot-hub/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: telemetry-to-azure-iot-hub
    steps:
      - uses: actions/checkout@v3
      - run: az bicep build --file main.bicep
      - run: ../.scripts/assert-azure-deploy-uri.sh telemetry-to-azure-iot-hub
