name: Build telemetry-to-azure-iot-hub

on:
  push:
    paths:
      - .github/workflows/telemetry-to-azure-iot-hub.yml
      - telemetry-to-azure-iot-hub/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: telemetry-to-azure-iot-hub
    steps:
      - uses: actions/checkout@v2
      - run: az bicep build --file main.bicep
      - run: ../scripts/assert-azure-deploy-uri.sh README.md https%3A%2F%2Fraw.githubusercontent.com%2FAxisCommunications%2Facap-integration-examples-azure%2Fmain%2Ftelemetry-to-azure-iot-hub%2Fmain.json
